
sudo: required
language: java

jdk:
  - oraclejdk8

script:
  - mvn clean cobertura:cobertura -Dtest=script#3 -DfailIfNoTests=false

before_deploy:
- tar -zcvf coverage-result.tar.gz /home/travis/build/leusonmario/android-maven-plugin/target/site/cobertura

deploy:
  provider: releases
  api_key:
    secure: "DHdE6EN3XSnYyZbHY/wYYOAcayOYGEMUI0004WP4w/F6xQgxJ3b/XgVnJMPp+RBB7H6I9uI9bjURIXC926E9VilauoXOPR4Rf6mvVd1TR32jM5vHa0Y6ugrGKPhLC4LWe6DVsI/KpaXrQhE1Jr6wUMGZFsx9w7LrYcuv+p4s3jD1vKJOTZCC6xtfCpUNmVJAfHl4zUJoOHfQHT02x6Z2oyX1yTbg6T5zrBgSkYieXBFMle68jflBjpygsRxPLL8xU7t8S4cY3UuaHt1geKpV+inQfeijo1CAcYqiqwpdTG4KCOk/Y/wxprdyYQi3vTBtR6iuyIGUJGhbPY82f7xVIjHKNSttv9UodRFFb+x5dmfTygLyY6fjJT0AVw80HDL8bwtpvLbDMX1Pm7kH0qEZmJ3wJGFrbdCyt+ANL6aD18SVl4W2C9BCnbK1CwCM0Ifukf97xPirK+HlWCoQWpHzXp4/40RRg2y8Q6bIToGBKPWJgusZsGLjZjogIEq4vE2TEUBVEpHixugqnZMzupF4G//k978rOUd2SK7caJrpEUFKMVU9DucAktAiX/CbmVgJTII7fNerU6mwdvr9n+Kt7yvs4p81+eV14H9K0zAja+458v25VHATrJOvcZvVJ6eaoi8FIVllOkZIcepvzJejmiKDHxtkBN1aZufK6C3S/Ps="


  file: coverage-result.tar.gz
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
