
sudo: required
language: java

jdk:
  - oraclejdk8

script:
  - mvn clean cobertura:cobertura -Dtest=MorseflashSampleIT#buildDeployAndRun -DfailIfNoTests=false

before_deploy:
- tar -zcvf coverage-result.tar.gz /home/travis/build/leusonmario/android-maven-plugin/target/site/cobertura

deploy:
  provider: releases
  api_key:
    secure: "bFX2kTucNkuLkVDpMXhTeQxpcwbt6e7gwbpiqMq/4T6E4OcJ9MjgWzsymMEeqB85ao8/D+7ZV3w+p9Jh1EDZty5oHYb8qj9EPCJ/+ow1jfuXXPxYhXI4OpEDdG2AA2FxewnkrgleCoOk2Y9O6wWVxKM8w765eNkc0aPNhf7+JGy46aWpd2sp7kcrLqmg+7HN3v20NFj3EkhIf4/IsHxprxFeFc5RNDkwXmXJgAQHngqdouhjPD3IFUBoiBW4tXq7I530N/0OYFIjjZNLS5RBbxOMxZaVgB90cNUrqTxyV4tMYqeUatwHlSXMEk8GRe76fPAMNjnoPkdEojR2jcJIwVE9WNvFTBa8BE4HGl+X+9NJQ0dc/RWwZUv6iW2JNeXGKDMC/I3y6B0YK9aQ+AtuesIfKBwL44FUSETYPyy04Y7Xucjar6Y2nrjPqJRsUyDtqCXzNaMAx/c+87GrIeN3QUvp6589lsnW7hD9/J9qmOR8p0d/aNoNZZtkMoo2xKoBzO5mql3voFiGv9o84ONU+2YreNtG6e74SvDF+TiGBLCTeCq+zpoEuD8omPQgSz2JDChgP7I7im2mZKdtqWCJOzsAYkBP6mjWV5zV2bMrLbb1vcES8fJt5qVX4uZ+DKa+ndgwx0c9AsXz4SXzPIB7fFfPNgdHhuG6bGwlmUQWErw="


  file: coverage-result.tar.gz
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
